### ISSUE TITLE
Query failing since last OCTI update to 5.12.25

### ISSUE THREAD

**Issue by biastogit** [rguignard/opencti-chrome-extension#3]
Hello, I love that plugin extension!
Unfortunately, after last update of OCTI to 5.12.25, the query to my opencti is not working anymore.
I debuged quickly and saw exactly the same error I had in another integration I have doing calls to the graphql api.
It seems something change in the schema.

The error in my debugger when the extension is trying to fetch results in OCTI is:

`[
    {
        "message": "Cannot query field \"edges\" on type \"Label\".",
        "locations": [
            {
                "line": 22,
                "column": 17
            }
        ],
        "extensions": {
            "code": "GRAPHQL_VALIDATION_FAILED"
        }
    }
]`

**Comment by biastogit** [comment]
I'm using v1.0.2

**Comment by rguignard** [comment]
merged
